name: sgkit-publication-popgen
channels:
- conda-forge
- defaults
dependencies:
- sgkit
- numpy < 1.24
- xarray
- dask[complete]
- dask-ml
- pandas
- scikit-learn
- scipy
- numba
- zarr
- rechunker
- jupyter
- pyprojroot
- matplotlib
- seaborn
