name: sgkit-publication-popgen
channels:
- conda-forge
- defaults
dependencies:
- pip
- numpy < 1.24
- xarray
- dask[complete]
- dask-ml
- pandas
- scikit-learn
- scipy
- numba
- zarr
- rechunker
- jupyter
- pyprojroot
- pip:
    - git+https://github.com/pystatgen/sgkit.git
